#!/bin/bash

source etc/banner
# Banner Add
echo -e "Yürütlüyor: ${LIGHTGREEN}KURULUM${NOCOLOR}"
echo "-----------------------"
# Setup directory for Requirements
quickbms_dir=$PREFIX/share/quickbms

function redirect {
 echo -e "${LIGHTGREEN}SethPAK BAŞLIYOR${NOCOLOR}"
 echo -ne '#####                     (23%)\r'
 sleep 1
 echo -ne '############              (57%)\r'
 sleep 1
 echo -ne '##################        (86%)\r'
 sleep 1
 echo -ne '#######################   (100%)\r'
 echo -ne '\n'
bash sethpak
}

function quickbms_check {
  echo -e "${YELLOW}Gerekli program kontrol ediliyor..${NOCOLOR}"
  FILE=$quickbms_dir/quickbms
  if [ -f "$FILE" ]; then
      echo -e "${LIGHTGREEN}Program kuruldu.${NOCOLOR}"
      redirect
  else 
      echo -e "${RED}PROGRAM BULUNAMADI.${NOCOLOR}"
      quickbms_install
      redirect
  fi
}

function quickbms_install {
  echo -e "${LIGHTGREEN}Gerekli program kuruluyor..${NOCOLOR}"
  wget -q http://aluigi.altervista.org/papers/quickbms_linux.zip
  sleep 1
  unzip -qq quickbms_linux.zip
  sleep 1
  mkdir $PREFIX/share/quickbms
  sleep 1
  chmod +x quickbms_4gb_files
  sleep 1
  yes | cp -rf quickbms_4gb_files $quickbms_dir/quickbms
  sleep 1
  chmod +x etc/tools.bms sethpak
  sleep 1
  rm -rf quickbms*
  rm setup
  mkdir output
}

#Checking Required Pakcages
echo -e "${YELLOW}Gerekli paketler kontrol ediliyor${NOCOLOR}"

packages=("wget" "unzip" "curl" "x11-repo" "qemu-system-i386" "qemu-user-i386")

for pkg in ${packages[@]}; do

    is_pkg_installed=$(dpkg-query -W --showformat='${Status}\n' ${pkg} | grep "install ok installed")

    if [ "${is_pkg_installed}" == "install ok installed" ]; then
        echo -e ${GREEN}${pkg}${NOCOLOR} yüklü.
    else [ "" = "${is_pkg_installed}" ];
     echo -e "${RED}No ${pkg}. kurulum ${pkg}.${NOCOLOR}" 
    pkg install ${pkg} -y
    fi
done
quickbms_check